// Wrapper pour charger les routes CommonJS depuis un module ES
// Utilise import() dynamique car les fichiers .js sont traités comme ES modules

async function loadRoutes() {
  const [
    notifications,
    shops,
    admin,
    settings,
    products,
    orders,
    payments,
    invoices,
    suppliers,
    returns,
    reports,
    categories,
    deliveries,
    quotes,
    recurringOrders,
    promotions,
    messages,
    search,
    exports,
    emails,
    security,
    auditLogs,
    manager,
    stock,
    prices,
    avatar,
    orderContext,
    clientShops,
    clientFinance
  ] = await Promise.all([
    import('./routes/notifications.js').then(m => m.default || m),
    import('./routes/shops.js').then(m => m.default || m),
    import('./routes/admin.js').then(m => m.default || m),
    import('./routes/settings.js').then(m => m.default || m),
    import('./routes/products.js').then(m => m.default || m),
    import('./routes/orders.js').then(m => m.default || m),
    import('./routes/payments.js').then(m => m.default || m),
    import('./routes/invoices.js').then(m => m.default || m),
    import('./routes/suppliers.js').then(m => m.default || m),
    import('./routes/returns.js').then(m => m.default || m),
    import('./routes/reports.js').then(m => m.default || m),
    import('./routes/categories.js').then(m => m.default || m),
    import('./routes/deliveries.js').then(m => m.default || m),
    import('./routes/quotes.js').then(m => m.default || m),
    import('./routes/recurring-orders.js').then(m => m.default || m),
    import('./routes/promotions.js').then(m => m.default || m),
    import('./routes/messages.js').then(m => m.default || m),
    import('./routes/search.js').then(m => m.default || m),
    import('./routes/exports.js').then(m => m.default || m),
    import('./routes/emails.js').then(m => m.default || m),
    import('./routes/security.js').then(m => m.default || m),
    import('./routes/audit-logs.js').then(m => m.default || m),
    import('./routes/manager.js').then(m => m.default || m),
    import('./routes/stock.js').then(m => m.default || m),
    import('./routes/prices.js').then(m => m.default || m),
    import('./routes/avatar.js').then(m => m.default || m),
    import('./routes/order-context.js').then(m => m.default || m),
    import('./routes/client-shops.js').then(m => m.default || m),
    import('./routes/client-finance.js').then(m => m.default || m)
  ]);

  return {
    notifications,
    shops,
    admin,
    settings,
    products,
    orders,
    payments,
    invoices,
    suppliers,
    returns,
    reports,
    categories,
    deliveries,
    quotes,
    recurringOrders,
    promotions,
    messages,
    search,
    exports,
    emails,
    security,
    auditLogs,
    manager,
    stock,
    prices,
    avatar,
    orderContext,
    clientShops,
    clientFinance
  };
}

module.exports = loadRoutes();
