/**
 * Définition des permissions et ressources
 */

export const RESOURCES = {
  CLIENTS: 'clients',
  STORES: 'stores',
  USERS: 'users',
  ORDERS: 'orders',
  PRODUCTS: 'products',
  STOCKS: 'stocks',
  INVOICES: 'invoices',
  SUPPLIERS: 'suppliers',  // ✅ Fournisseurs (ADMIN uniquement)
  COMMISSIONS: 'commissions',  // ✅ Commissions Fattah (ADMIN uniquement)
}

export const ACTIONS = {
  READ: 'read',
  CREATE: 'create',
  UPDATE: 'update',
  DELETE: 'delete',
}

/**
 * Matrice de permissions par rôle
 */
export const PERMISSIONS = {
  ADMIN: {
    [RESOURCES.CLIENTS]: [ACTIONS.READ, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.STORES]: [ACTIONS.READ, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.USERS]: [ACTIONS.READ, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE],
    [RESOURCES.ORDERS]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.PRODUCTS]: [ACTIONS.READ, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE],
    // ❌ STOCKS supprimé - ADMIN (Fattah) ne gère AUCUN stock
    [RESOURCES.INVOICES]: [ACTIONS.READ],
    [RESOURCES.SUPPLIERS]: [ACTIONS.READ, ACTIONS.CREATE, ACTIONS.UPDATE, ACTIONS.DELETE],  // ✅ Fournisseurs
    [RESOURCES.COMMISSIONS]: [ACTIONS.READ],  // ✅ Commissions
  },
  CLIENT: {
    [RESOURCES.ORDERS]: [ACTIONS.READ, ACTIONS.CREATE],
    [RESOURCES.PRODUCTS]: [ACTIONS.READ],
    [RESOURCES.STOCKS]: [ACTIONS.READ],
    [RESOURCES.INVOICES]: [ACTIONS.READ],
  },
  MANAGER: {
    [RESOURCES.ORDERS]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.PRODUCTS]: [ACTIONS.READ],
    [RESOURCES.STOCKS]: [ACTIONS.READ, ACTIONS.UPDATE],
  },
  PREPARATEUR: {
    [RESOURCES.ORDERS]: [ACTIONS.READ, ACTIONS.UPDATE],
    [RESOURCES.STOCKS]: [ACTIONS.READ, ACTIONS.UPDATE],
  },
  LIVREUR: {
    [RESOURCES.ORDERS]: [ACTIONS.READ, ACTIONS.UPDATE],
  },
}
